name: Edward Fox
favicon: null
layout_spectrum: 0.33118595369160175
typography_spectrum: 0.7606493418570608
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.18256958900019526
  lightness: 0.060666697565466166
  saturation: 0.37572714779525995
  rhythmicContrast: 0.49663449986837804
purpose: []
