analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.07388
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.37572714779526
  brandStrength: 0.25
  rhythmicContrast: 0.75
  brandColors:
    - '#f3f1e5'
    - '#000002'
    - '#494039'
    - '#9a8f73'
    - '#d0440f'
  lightness: 0.06066669756546617
purpose: []
favicon: null
name: Edward Fox
typography_spectrum: 0.33129
