name: Edward Fox
favicon: null
layout_spectrum: 0.33118595369160175
typography_spectrum: 0.7606493418570608
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f1e5'
    - '#000002'
    - '#494039'
    - '#9a8f73'
    - '#d0440f'
  brandStrength: 0.25
  lightness: 0.060666697565466166
  saturation: 0.37572714779525995
  rhythmicContrast: 0.75
purpose: []
